host: 0.0.0.0
port: 8080

subdomains: nested

admin:
  host: localhost
  port: 6060

registries:
  default:
  - https://apps-registry.cozycloud.cc/
  - https://apps-registry.cozycloud.cc/selfhosted
  - https://apps-registry.cozycloud.cc/banks

fs:
  url: file://localhost/cozy/storage

couchdb:
  url: http://cozy-couchdb:5984/

log:
  level: info
  syslog: false
